### ISSUE TITLE
Customize TicketBird Instructions Message

### ISSUE THREAD

**Issue by smnc** [NovaFox161/TicketBird-Discord-Bot#13]
![image](https://user-images.githubusercontent.com/19196582/95249350-83cc2a00-07e6-11eb-9054-e63fb6c30894.png)
I'd love to be able to change the default message to suit my goup's needs.

It'd also be fantastic to be able to customize this message:
![image](https://user-images.githubusercontent.com/19196582/95249620-f3dab000-07e6-11eb-9cf5-e5e3731f07e9.png)

**Comment by NovaFox161** [comment]
TicketBird now supports changing the default message, with the second message customization following soon. 

Check out the 2.1.1 release notes: [tag#2.1.1](https://github.com/DreamExposure/TicketBird-Discord-Bot/releases/tag/2.1.1)
